static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 3307
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: db_tcp
          cluster: mysql
  clusters:
  - name: mysql
    connect_timeout: 1s
    type: static
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 3306
  - name: zipkin
    connect_timeout: 1s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 10.0.1.100
        port_value: 9411
admin:
  access_log_path: "/tmp/admin-access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
