global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: envoy
    metrics_path: '/stats/prometheus'
    static_configs:
      - targets: ['192.168.121.14:9901']
        labels:
          group: app
          app: server1
      - targets: ['192.168.121.246:9901']
        labels:
          group: app
          app: server2

  - job_name: node-exporter
    static_configs:
      - targets: ['192.168.121.14:9100']
        labels:
          group: app
          app: server2
        
      - targets: ['192.168.121.246:9100']
        labels:
          group: app
          app: server2
        
      - targets: ['192.168.121.189:9100']
        labels:
          group: db
          app: server3

  - job_name: mysql
    static_configs:
      - targets: ['192.168.121.189:9104']
        labels:
          group: db
          app: server3
